import ENV_VARS from "../../tools/ENV_VARS.js"

export default {
  CHECK_STATUS_URL_FUNC: ENV_VARS.SERVER_STATUS_URL_FUNC,
  TRANSPILE_URL_FUNC: ENV_VARS.SERVER_TRANSPILATION_URL_FUNC,
  UPDATE_STATUS: 'UPDATE_STATUS'
}
